# Generated by Django 4.0.6 on 2023-04-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
