# Generated by Django 4.0.6 on 2023-04-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_topic_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='email',
        ),
    ]
